import subprocess, time
from playwright.sync_api import sync_playwright
srv = subprocess.Popen(["python", "-m", "http.server", "8770", "-d", "site"]); time.sleep(1)
with sync_playwright() as p:
    b = p.chromium.launch()
    mp = b.new_page(**p.devices["iPhone 13"]); errs = []; mp.on("pageerror", lambda e: errs.append(str(e)))
    mp.goto("http://localhost:8770/"); mp.wait_for_timeout(2000)
    mp.click("#vMap"); mp.wait_for_timeout(3000)
    btn0 = mp.locator("#toMap").is_visible()
    pins = mp.locator(".pin"); pins.nth(pins.count() // 2).click(force=True); mp.wait_for_timeout(1500)
    btn1 = mp.locator("#toMap").is_visible()
    mp.screenshot(path="shot_phone_list.png")
    mp.click("#toMap"); mp.wait_for_timeout(1500)
    maptop = mp.evaluate("document.getElementById('map').getBoundingClientRect().top")
    btn2 = mp.locator("#toMap").is_visible(); popup = mp.locator(".leaflet-popup").count()
    mp.screenshot(path="shot_phone_back.png")
    mp.evaluate("window.scrollBy(0, 1500)"); mp.wait_for_timeout(600)
    mp.locator("#mapList [data-locate]").nth(2).click(); mp.wait_for_timeout(1800)
    maptop2 = mp.evaluate("document.getElementById('map').getBoundingClientRect().top")
    print("errors:", errs, "btn_initial:", btn0, "btn_after_scroll:", btn1, "after_back map_top:", round(maptop), "btn:", btn2, "popup:", popup, "locate map_top:", round(maptop2))
    b.close()
srv.kill()
